### PR TITLE
fix interactive edge

### LINKED ISSUE #3648: 工作流如果存在多个回退线路无法正常执行
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图，配置文件等**
目前的现象是，当工作流执行过一次回退线路时，后续再遇到回退节点（即有多个输入箭头的节点）流程会中断。

**复现步骤**
以下是我简化后的一个复现流程
Image

Image

Image

当选过返回上一步后，后续再选下一步会直接中断：
Image

没有返回的场景工作正常：
Image

**预期结果**
正常应该是无论我怎么选择路线，最终应该都能走到step 3

**相关截图**

### PR DESCRIPTION
**Pull request by newfish-cmyk**
fix #3648

### CODE REVIEW

**Comment by c121914yu** [comment]
# 🤖 Generated by deploy action
📦 Preview Image: `ghcr.io/labring/fastgpt-pr:ac01f7c81c86cbee957183bf4d3c5e6882538b22`

File: packages/global/core/workflow/runtime/utils.ts [hunk 1]
```diff
@@ -215,11 +215,11 @@ export const checkNodeRunStatus = ({
     return 'skip';
   }
 
-  // check active（有一类边，不全是 wait 即可运行）
-  if (commonEdges.length > 0 && commonEdges.every((item) => item.status !== 'waiting')) {
+  // check active（有一类边，有 active）
```
Comment (c121914yu) [inline packages/global/core/workflow/runtime/utils.ts:218]: 不行吧，两个接入的话，一个到达了不就执行了

**Review by c121914yu — APPROVED** [review]
